const skills={critical:{name:'التفكير النقدي',icon:'◉',tone:'critical',description:'افحص الأفكار، اسأل عن الأدلة، وابنِ رأيًا أكثر وعيًا.',prompt:'انتشر خبر على وسائل التواصل يقول إن العمل عن بُعد يقلل الإنتاجية بنسبة كبيرة. كيف ستقيّم صحة هذا الادعاء قبل أن تبني موقفك؟',level:'متوسط',hint:'ابدأ بتحديد مصدر الخبر، ثم اسأل: ما المقصود بالإنتاجية؟ وهل توجد حالات أو بيانات تناقضه؟'},creative:{name:'التفكير الإبداعي',icon:'✧',tone:'creative',description:'حرّر خيالك، واربط بين الأشياء بطريقة لم تُجرّب من قبل.',prompt:'تخيّل أن مدينتك قررت إغلاق شارع رئيسي للسيارات يومًا واحدًا كل أسبوع. ما الاستخدامات الجديدة التي يمكن أن تمنح هذا الشارع حياة مختلفة؟',level:'سهل',hint:'لا تتوقف عند الفكرة الأولى. فكّر في احتياجات الأطفال، كبار السن، الفنانين، أو أصحاب المشاريع الصغيرة.'},problem:{name:'حل المشكلات',icon:'⌁',tone:'problem',description:'فكك المواقف المعقدة، واكتشف مسارات عملية للتقدم.',prompt:'فريقك يتأخر دائمًا في تسليم المشاريع، رغم أن الجميع يعمل بجد. كيف ستبحث عن أصل المشكلة وتقترح تجربة أولى لتحسين الوضع؟',level:'متقدم',hint:'فرّق بين العرض والسبب. راقب أين يتراكم العمل، واسأل أعضاء الفريق عن العوائق غير المرئية.'}};
let state=JSON.parse(localStorage.getItem('fikra-state')||'{"completed":0,"scores":[],"skills":{}}');let currentSkill='critical';const arabicNumber=n=>String(Math.round(n)).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d]);const $=id=>document.getElementById(id);
function skillCard(key,detailed=false){const s=skills[key];return `<article class="skill-card ${s.tone}"><div class="skill-icon">${s.icon}</div><span class="card-arrow">↗</span><h3>${s.name}</h3><p>${s.description}</p>${detailed?`<button class="start-card" data-skill="${key}">ابدأ التحدي ←</button>`:''}</article>`}
function renderSkills(){$('skill-preview').innerHTML=Object.keys(skills).map(k=>skillCard(k)).join('');$('skill-list').innerHTML=Object.keys(skills).map(k=>skillCard(k,true)).join('');document.querySelectorAll('[data-skill]').forEach(b=>b.addEventListener('click',()=>startChallenge(b.dataset.skill)))}
function navigate(page){const targetPage=page==='how'?'home':page;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active-page',p.id===targetPage));document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===targetPage));if(page==='how'){document.getElementById('how').scrollIntoView({behavior:'smooth'});return}window.scrollTo({top:0,behavior:'smooth'});if(targetPage==='progress')renderProgress()}
function startChallenge(key){currentSkill=key;const s=skills[key];$('challenge-tag').textContent=s.name;$('challenge-level').textContent=s.level;$('challenge-title').textContent='تحدٍ يوسّع طريقة نظرك';$('challenge-prompt').textContent=s.prompt;$('answer').value='';$('hint-box').hidden=true;navigate('challenge')}
function analyze(){const answer=$('answer').value.trim();if(answer.length<15){showToast('اكتب بضعة أسطر حتى نستطيع التفكير معًا.');$('answer').focus();return}const score=Math.min(94,62+Math.round(answer.length/10));$('overall-score').textContent=arabicNumber(score);$('answer-preview').textContent=answer;$('criteria').innerHTML=[['وضوح الفكرة',Math.min(95,score+7)],['قوة التحليل',Math.max(55,score-4)],['المنطق',Math.min(92,score+2)],['الإبداع',Math.max(52,score-9)],['زوايا متعددة',Math.max(48,score-14)]].map(([n,v])=>`<div class="criterion"><div class="criterion-head"><span>${n}</span><b>${arabicNumber(v)}٪</b></div><div class="meter"><i style="width:${v}%"></i></div></div>`).join('');$('reflection-questions').innerHTML=['ما الافتراض الذي بنيت عليه إجابتك؟','هل توجد وجهة نظر أخرى لم تمنحها مساحة؟','ما الأدلة التي تدعم قرارك؟','ماذا سيحدث إذا تغير أحد عوامل المشكلة؟'].map(q=>`<div class="question"><span>؟</span><div>${q}</div></div>`).join('');navigate('feedback')}
function complete(){const score=parseInt($('overall-score').textContent.replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)))||72;state.completed++;state.scores.push(score);state.skills[currentSkill]=(state.skills[currentSkill]||0)+1;localStorage.setItem('fikra-state',JSON.stringify(state));showToast('أحسنت، أُضيف التحدي إلى رحلتك.');navigate('progress')}
function renderProgress(){const avg=state.scores.length?state.scores.reduce((a,b)=>a+b,0)/state.scores.length:0;const percent=Math.min(100,state.completed*12);$('completed-count').textContent=arabicNumber(state.completed);$('average-score').textContent=arabicNumber(avg)+'٪';$('journey-percent').textContent=arabicNumber(percent)+'٪';$('header-score').textContent=arabicNumber(percent)+'٪';$('level-name').textContent=state.completed>4?'مفكر متقدم':state.completed>1?'مستكشف واعٍ':'بداية واعية';$('level-detail').textContent=state.completed?`أنجزت ${arabicNumber(state.completed)} تحديات حتى الآن`:'أول خطوة في الرحلة';$('skill-progress').innerHTML=Object.keys(skills).map(k=>{const v=state.skills[k]?Math.min(100,state.skills[k]*25):0;return `<div class="skill-progress"><div class="skill-progress-row"><span>${skills[k].name}</span><b>${arabicNumber(v)}٪</b></div><div class="meter"><i style="width:${v}%"></i></div></div>`}).join('');$('encouragement-text').textContent=state.completed?'أنت تبني عادة التفكير، محاولة بعد أخرى.':'كل سؤال جيد هو طريقة جديدة لرؤية العالم.'}
function showToast(text){const t=$('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
document.addEventListener('click',e=>{const target=e.target.closest('[data-page]');if(target){e.preventDefault();navigate(target.dataset.page)}if(e.target.closest('#mobile-menu'))document.querySelector('.main-nav').classList.toggle('open')});
renderSkills();$('analyze-btn').addEventListener('click',analyze);$('hint-btn').addEventListener('click',()=>{$('hint-box').textContent=skills[currentSkill].hint;$('hint-box').hidden=false});$('retry-btn').addEventListener('click',()=>navigate('challenge'));$('complete-btn').addEventListener('click',complete);renderProgress();